name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - ".github/workflows/unit-tests.yaml"

jobs:
  unit-test:
    name: Execute all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: false
      - name: Execute unit tests
        run: go test -v ./...